name: BioDyn CI

# ───────────────────────────────────────────────
# 1. Triggers
# ───────────────────────────────────────────────
on:
  push:
    branches: [ main, dev, staging ]
  pull_request:

# ───────────────────────────────────────────────
# 2. Global settings
# ───────────────────────────────────────────────
env:
  PYTHON_VERSION: "3.11"   # keep in sync with your requirements.txt

jobs:
  # ────────────────────────────────────────────
  # Job: lint & test
  # ────────────────────────────────────────────
  test:
    runs-on: ubuntu-latest

    steps:
    # 2-1  Check out your code
    - name: Checkout repo
      uses: actions/checkout@v4

    # 2-2  Install the chosen Python and enable pip-cache
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: "pip"                       # free pip cache :contentReference[oaicite:0]{index=0}

    # 2-3  Install dependencies + dev tools
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8 coverage

    # 2-4  Static check (flake8)
    - name: Lint with flake8
      run: flake8 .

    # 2-5  Run unit tests
    - name: Run pytest
      run: pytest -q

    # 2-6  (Optional) collect coverage – GitHub displays summary automatically
    - name: Upload coverage to summary
      if: always()                       # still runs even if tests fail
      run: |
        coverage run -m pytest
        coverage xml
    - name: Report coverage
      if: success()
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # set once in repo → Settings → Secrets

