name: BioDyn CI

on:
  push:
    branches: [ main, dev, staging ]
  pull_request:

env:
  PYTHON_VERSION: "3.11"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # ── checkout ───────────────────────────
    - uses: actions/checkout@v4

    # ── Python + pip cache ────────────────
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: pip

    # ── install deps ──────────────────────
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest coverage flake8

    # ── Lint (non-blocking for now) ───────
    - name: Lint with flake8 (warn-only)
      run: flake8 . || true      # remove `|| true` once code is clean

    # ── Run tests + coverage ──────────────
    - name: Run pytest with coverage
      run: |
        coverage run -m pytest -q
        coverage xml

    # ── Upload coverage report ────────────
    - name: Upload to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}   # optional for public repos

